---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: "harbor-${MOLECULE_DISTRO:-ubuntu2204}"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    environment:
      container: docker

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
  config_options:
    defaults:
      remote_user: root
    privilege_escalation:
      become: false
  inventory:
    host_vars:
      "harbor-${MOLECULE_DISTRO:-ubuntu2204}":
        ansible_user: root

verifier:
  name: ansible
