---
name: Molecule

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: 'ialejandro.harbor'

jobs:
  molecule:
    name: Molecule - ${{ matrix.distro }}
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        distro:
          - amazonlinux2023
          - debian12
          - ubuntu2204
          - ubuntu2404
          - rockylinux9

    steps:
      - name: Check out the codebase
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          path: 'ialejandro.harbor'

      - name: Set up Python3
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: '3.13' # Can't go to 3.14+ until Ansible 13.x

      - name: Install dependencies
        run: pip3 install ansible molecule molecule-plugins[docker]

      - name: Run Molecule tests
        run: molecule test
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
